import { BarChart3, Box, ChevronDown, Package, Search, ShoppingCart } from 'lucide-react'

const navItems = [{ icon: BarChart3, label: 'Overview' }, { icon: ShoppingCart, label: 'Orders' }, { icon: Package, label: 'Products' }, { icon: Box, label: 'Inventory' }]

export function ProductPreview() {
  return <div className="overflow-hidden rounded-2xl border border-ink-200 bg-white shadow-[0_24px_80px_-32px_rgba(23,26,31,.35)]">
    <div className="flex items-center justify-between border-b border-ink-100 px-5 py-3"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-[#e8a08c]" /><span className="h-2.5 w-2.5 rounded-full bg-[#e8cb8c]" /><span className="h-2.5 w-2.5 rounded-full bg-[#9bc7a9]" /></div><div className="font-mono text-[10px] text-ink-400">FINCH DESKTOP / 2.4.1</div></div>
    <div className="grid min-h-[390px] grid-cols-[156px_1fr] bg-[#f8faf8]">
      <aside className="border-r border-ink-100 bg-white p-4"><div className="mb-8 flex items-center gap-2 text-xs font-semibold"><span className="grid h-6 w-6 place-items-center rounded-md bg-brand-600 text-[10px] text-white">F</span> Finch</div><div className="space-y-1">{navItems.map(({ icon: Icon, label }, index) => <div key={label} className={`flex items-center gap-2 rounded-md px-2.5 py-2 text-[11px] ${index === 0 ? 'bg-brand-50 font-semibold text-brand-700' : 'text-ink-500'}`}><Icon size={13} />{label}</div>)}</div><div className="mt-8 border-t border-ink-100 pt-4 text-[10px] text-ink-400">WORKSPACE<br /><span className="mt-2 inline-block text-ink-600">Acme Supply Co.</span></div></aside>
      <main className="p-6"><div className="mb-6 flex items-start justify-between"><div><div className="font-mono text-[9px] uppercase tracking-widest text-brand-600">Monday, October 21</div><h3 className="mt-1 text-lg font-semibold tracking-tight">Good morning, Alex</h3></div><div className="flex items-center gap-2 rounded-md border border-ink-200 bg-white px-2.5 py-2 text-[10px] text-ink-500"><Search size={12} /> Search</div></div><div className="grid grid-cols-3 gap-3">{[['Revenue', '$84,230', '+12.8%'], ['Orders', '1,284', '+8.4%'], ['Customers', '642', '+16.2%']].map(([title, value, change]) => <div key={title} className="rounded-lg border border-ink-100 bg-white p-3"><div className="text-[10px] text-ink-500">{title}</div><div className="mt-2 text-base font-semibold">{value}</div><div className="mt-1 text-[9px] font-medium text-brand-600">{change} this month</div></div>)}</div><div className="mt-4 grid grid-cols-[1.5fr_1fr] gap-3"><div className="rounded-lg border border-ink-100 bg-white p-4"><div className="flex justify-between text-[10px] font-semibold"><span>Revenue overview</span><span className="flex items-center gap-1 font-normal text-ink-400">Last 30 days <ChevronDown size={11} /></span></div><div className="mt-6 flex h-28 items-end gap-2">{[38,52,46,68,55,72,63,84,71,92,78,100,88,95].map((height, i) => <div key={i} className="flex-1 rounded-t-sm bg-brand-200 transition-colors hover:bg-brand-500" style={{ height: `${height}%` }} />)}</div></div><div className="rounded-lg border border-ink-100 bg-white p-4"><div className="text-[10px] font-semibold">Top products</div>{[['Nimbus Chair','$12,840'],['Field Lamp','$8,920'],['Arc Desk','$6,450']].map(([name, value], i) => <div key={name} className="mt-4 flex items-center justify-between text-[10px]"><span className="flex items-center gap-2"><span className="grid h-5 w-5 place-items-center rounded bg-accent-100 font-mono text-[8px] text-accent-700">0{i + 1}</span>{name}</span><span className="font-medium">{value}</span></div>)}</div></div></main>
    </div>
  </div>
}
